name: "openscpca-metacells"
channels:
  - conda-forge
  - bioconda
  - defaults
platforms:
  - linux-64
  - osx-64
  - osx-arm64
dependencies:
  - python=3.11
  - awscli>=2.15
  - conda-lock>=2.5
  - jq>=1.7
  - pre-commit>=3.6
  - session-info>=1.0
  - anndata
  - cycler
  - fcsparser
  - h5py
  - jax
  - jaxopt
  - leidenalg
  - matplotlib
  - mellon
  - numpy
  - pandas
  - progressbar2
  - pygam==0.9.0
  - python-utils
  - scanpy
  - scikit-learn
  - scipy=1.11
  - seaborn
  - statsmodels
  - tabulate
  - tqdm
  - umap-learn
  - pip
  - pip:
      - pyranges
      - SEACells==0.3.3
