name: openscpca-hello-python
channels:
  - conda-forge
  - bioconda
  - defaults
platforms:
  - linux-64
  - osx-64
  - osx-arm64
dependencies:
  - python=3.11
  - anndata=0.10
  - awscli=2.15
  - conda-lock=2.5
  - gitpython=3.1
  - jq=1.7
  - jupyter=1.0
  - pandas=2.2
  - pre-commit=3.6
  - session-info=1.0
