[files]
extend-exclude = [
  "**.html",
  "**.tsv",
  "docs/policies/*md", # ignore legal
]



[default.extend-words]
enure="enure" # legal
CNA="CNA" # actually copy-number alteration


[default.extend-identifiers]
glmGamPoi="glmGamPoi"
NBAltas="NBAltas"
abd58442="abd58442" # A Jupyter notebook id that appears in the template Jupyter notebook, so it appears across the repo
24dbe4e6="24dbe4e6" # Another Jupyter notebook id that it wants to correct

[default]
extend-ignore-re = [
  # various variables in cell-type-wilms-tumor-06, and we don't want to ignore "thr"
  '\baucThr\b',
  '\bpred\.thr\b',
  '\bcnv\.thr\.lower\b',
  '\bcnv\.thr\.upper\b',
  '\bpredicted\.score_thr\b'
]
