[files]
extend-exclude = [
  "**.html",
  "**.tsv",
  "docs/policies/*md", # ignore legal
]


[default.extend-words]
CNA="CNA" # actually copy-number alteration


[default.extend-identifiers]
glmGamPoi="glmGamPoi"
aucThr="aucThr" # cell-type-ewings module
pred_thr="pred_thr"  # cell-type-wilms-06 module
score_thr="score_thr" # cell-type-wilms-06 module

[type.ipynb]
extend-glob = ["**.ipynb"]
extend-ignore-re = [
  '"id": "\w{8}"'  # ignore Jupyter notebook ids
]
