[files]
extend-exclude = [
  "**.html",
  "**.tsv",
  "docs/policies/*md", # ignore legal
]


[default.extend-words]
CNA="CNA" # actually copy-number alteration


[default.extend-identifiers]
glmGamPoi="glmGamPoi"

[default]
extend-ignore-re = [
  # various variables in cell-type-wilms-tumor-06, and we don't want to ignore "thr"
  '\baucThr\b',
  '\bpred\.thr\b',
  '\bcnv\.thr\.lower\b',
  '\bcnv\.thr\.upper\b',
  '\bpredicted\.score_thr\b'
]

[type.ipynb]
extend-glob = ["**.ipynb"]
extend-ignore-re = [
  '"id": "\w{8}"'  # ignore Jupyter notebook ids
]
