name: "openscpca-{{ openscpca_module }}"
channels:
  - conda-forge
  - bioconda
  - defaults
platforms:
  - linux-64
  - osx-64
  - osx-arm64
dependencies:
  - python=3.11
  - awscli>=2.15
  - conda-lock>=2.5
  - jupyter=1.0
  - jq>=1.7
  - pre-commit>=3.6
  - session-info>=1.0
