name: openscpca-cell-type-scimilarity
channels:
  - conda-forge
  - bioconda
  - pytorch
platforms:
  - linux-64
  - osx-arm64
dependencies:
  - python=3.10
  - awscli>=2.15
  - conda-lock>=2.5
  - anndata
  - numba
  - llvmlite
  - pytorch
  - pip
  - pip:
    - scimilarity
