name: Build Docker image for cell-type-ewings

concurrency:
  # only one run per branch at a time
  group: "docker_cell-type-ewings_${{ github.ref }}"
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    paths:
      - analyses/cell-type-ewings/Dockerfile
      - analyses/cell-type-ewings/.dockerignore
      - analyses/cell-type-ewings/renv.lock
      - analyses/cell-type-ewings/conda-lock.yml
  push:
    branches:
      - main
    paths:
      - analyses/cell-type-ewings/Dockerfile
      - analyses/cell-type-ewings/.dockerignore
      - analyses/cell-type-ewings/renv.lock
      - analyses/cell-type-ewings/conda-lock.yml
  workflow_dispatch:
    inputs:
      push-ecr:
        description: "Push to AWS ECR"
        type: boolean
        required: false
  workflow_call:
    inputs:
      push-ecr:
        description: "Push to AWS ECR"
        type: boolean

jobs:
  test-build:
    name: Test Build Docker Image
    if: github.event_name == 'pull_request' || (contains(github.event_name, 'workflow_') && !inputs.push-ecr)
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:analyses/simulate-sce"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build:
    name: Build Docker Image
    if: github.repository_owner == 'AlexsLemonade' && (github.event_name == 'push' || inputs.push-ecr)
    uses: ./.github/workflows/build-push-docker-module.yml
    with:
      module: cell-type-ewings
      push-ecr: false

  push:
    name: Push Docker Image
    if: github.repository_owner == 'AlexsLemonade' && (github.event_name == 'push' || inputs.push-ecr)
    uses: ./.github/workflows/build-push-docker-module.yml
    with:
      module: cell-type-ewings
      push-ecr: true
