# This is a workflow to run the cell-type-scimilarity module
#
# Analysis modules are run based on three triggers:
# - Manual trigger
# - On pull requests where code in the module has changed
# - As a reusable workflow called from a separate workflow which periodically runs all modules
#
# At initialization, only the manual trigger is active

name: Run cell-type-scimilarity analysis module
env:
  MODULE_PATH: analyses/cell-type-scimilarity
  AWS_DEFAULT_REGION: us-east-2

concurrency:
  # only one run per branch at a time
  group: "run_cell-type-scimilarity_${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - analyses/cell-type-scimilarity/**
      - "!analyses/cell-type-scimilarity/Dockerfile"
      - "!analyses/cell-type-scimilarity/.dockerignore"
      - .github/workflows/run_cell-type-scimilarity.yml

jobs:
  run-module:
    if: github.repository_owner == 'AlexsLemonade'
    runs-on: ubuntu-latest
    container: public.ecr.aws/openscpca/cell-type-scimilarity:latest
    defaults:
      run: 
        shell: bash -el {0}

    steps:
      - name: Clear space
        run: |
          echo "Disk space before cleanup:"
          df -h
          # Software to remove
          # see https://mathio28.medium.com/squeezing-disk-space-from-github-actions-runners-an-engineers-guide-d5fbe4443692
          sudo rm -rf \
            /usr/lib/jvm \
            /usr/share/dotnet \
            /usr/share/swift \
            /usr/local/.ghcup \
            /usr/local/.rustup \
            /usr/local/julia* \
            /usr/local/lib/android \
            /usr/local/share/powershell \
            /opt/hostedtoolcache

          echo "Disk space after cleanup:"
          df -h

      - name: Checkout repo
        uses: actions/checkout@v4
        
      # Update this step as needed to download the desired data
      # pick a few random projects for now
      - name: Download test data
        run: |
          conda activate openscpca-cell-type-scimilarity
          ./download-data.py --test-data --format AnnData --project SCPCP000001,SCPCP000005,SCPCP000010,SCPCP000015

      - name: Run analysis module
        run: |
          conda activate openscpca-cell-type-scimilarity
          projects=$(basename -a data/current/SCPCP*)

          cd ${MODULE_PATH}
          ./setup-analysis.sh
          
          for project in $projects; do
              ./run-scimilarity.sh $project
          done
