# This is a workflow to run the cell-type-wilms-tumor-06 module
#
# Analysis modules are run based on three triggers:
# - Manual trigger
# - On pull requests where code in the module has changed
# - As a reusable workflow called from a separate workflow which periodically runs all modules
#
# At initialization, only the manual trigger is active

name: Run cell-type-wilms-tumor-06 analysis module
env:
  MODULE_PATH: analyses/cell-type-wilms-tumor-06
  AWS_DEFAULT_REGION: us-east-2

concurrency:
  # only one run per branch at a time
  group: "run_cell-type-wilms-tumor-06_${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
      - feature/*
    paths:
      - analyses/cell-type-wilms-tumor-06/**
      - "!analyses/cell-type-wilms-tumor-06/Dockerfile"
      - "!analyses/cell-type-wilms-tumor-06/.dockerignore"
      - .github/workflows/run_cell-type-wilms-tumor-06.yml

jobs:
  run-module:
    if: github.repository_owner == 'AlexsLemonade'
    runs-on: ubuntu-latest
    container: public.ecr.aws/openscpca/cell-type-wilms-tumor-06:latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install aws-cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Download test data
        env:
          # Use all samples for testing unless this is triggered by a PR, in which case only use a subset of samples for faster testing
          # These samples were selected either because:
          # - they are the subset of samples explored when evaluating CNV methods, so they must be present to run the module workflow in full
          # - they do not use a reference with inferCNV so we would like to test that they are properly handled
          DOWNLOAD_FLAG: ${{ github.event_name != 'pull_request' && '--projects SCPCP000006' || '--samples SCPCS000179,SCPCS000184,SCPCS000194,SCPCS000205,SCPCS0000208,SCPCS000177,SCPCS000190' }}
        run: |
          ./download-data.py --test-data --format SCE ${DOWNLOAD_FLAG}
          ./download-data.py --test-data --metadata-only --projects SCPCP000006


      - name: Run analysis module
        run: TESTING=1 bash 00_run_workflow.sh
        working-directory: ${{ env.MODULE_PATH }}
