# This is a workflow to run the hello-python module
# Analysis modules are run based on three triggers:
# - Manual trigger
# - On pull requests where code in the module has changed
# - As a reusable workflow called from a separate workflow which periodically runs all modules

name: Run hello-python analysis module
env:
  MODULE_PATH: analyses/hello-python
  AWS_DEFAULT_REGION: us-east-2

concurrency:
  # only one run per branch at a time
  group: "run_hello-python_${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - analyses/hello-python/**

jobs:
  run-module:
    if: github.repository_owner == 'AlexsLemonade'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3

      - name: Install and activate locked conda environment
        run: |
          conda install conda-lock
          conda-lock install --name test ${MODULE_PATH}/conda-lock.yml

      - name: Download test data
        run: ./download-data.py --test-data --format AnnData

      - name: Run analysis
        run: |
          cd $MODULE_PATH
          bash run_hello-python.sh
